{% set name = "ansible-compat" %}
{% set version = "1.0.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ansible-compat-{{ version }}.tar.gz
  sha256: 2ade2acbd1d7868eeb602c682afe92bc8c05480333205c328b4c2a1b09f970a4

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
    - setuptools_scm >=3.5.0
    - setuptools_scm_git_archive >=1.0
  run:
    - cached-property ~=1.5  # [py<=37]
    - python
    - pyyaml
    - subprocess-tee

test:
  imports:
    - ansible_compat
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ansible-community/ansible-compat
  summary: Ansible compatibility goodies
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - tschoonj
