{% set name = "ansible-compat" %}
{% set version = "2.2.5" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ansible-compat-{{ version }}.tar.gz
  sha256: 28c7c545fd60ef9c3059cfb2fefd27f92db091ff6b5868f83f121ceb5e1fe1b5

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools_scm >=3.5.0
    - setuptools_scm_git_archive >=1.0
  run:
    - python >=3.8
    - jsonschema
    - pyyaml
    - subprocess-tee
    - packaging

test:
  imports:
    - ansible_compat
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ansible-community/ansible-compat
  summary: Ansible compatibility goodies
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - tschoonj
